services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_API_WS_URL: ${NEXT_PUBLIC_API_WS_URL}
        NEXT_PUBLIC_MEET_URL: ${NEXT_PUBLIC_MEET_URL}
        NEXT_PUBLIC_MEET_WS_URL: ${NEXT_PUBLIC_MEET_WS_URL}
        NEXT_PUBLIC_CONVERSATION_URL: ${NEXT_PUBLIC_CONVERSATION_URL}
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_OR_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_OR_ANON_KEY}
    container_name: fe-da1-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
